### ISSUE TITLE
How to submit the result on the leaderborad?

### ISSUE THREAD

**Issue by Hon-Wong** [OpenGVLab/MMIU#4]
Great works!

I was wandering how to submit my result on the leaderboard?

Thanks in advance!

**Comment by FanqingM** [comment]
Thank you for your attention. You can give us the results (https://github.com/OpenGVLab/MMIU/blob/main/evaluate_correct.py) and we will update it on the website.

**Comment by FanqingM** [comment]
Feel free to contact me with [mengfanqing33@gmail.com](mailto:mengfanqing33@gmail.com)

**Comment by Hon-Wong** [comment]
Thank you!
